### 상품 추가
POST http://localhost:8082/seller/product
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0QnRyc3BBMWM0Z1MvSFRGcHBZYkxqTnQ4YXBkSmxYOG54djlYamhYNkJFPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjgwMzEzMzMzLCJleHAiOjE2ODAzOTk3MzN9.ZQgNMHhC-e4r9ZwbIua2tovKz99US-PfywYuXEQSGgs

{
  "description": "상품설명",
  "items": [
    {
      "count": 1,
      "name": "1234",
      "price": 10000
    }
  ],
  "name": "나이키 에어포스"
}

### 상품 아이템 추가
POST http://localhost:8082/seller/product/item
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0QnRyc3BBMWM0Z1MvSFRGcHBZYkxqTnQ4YXBkSmxYOG54djlYamhYNkJFPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjgwMzEzMzMzLCJleHAiOjE2ODAzOTk3MzN9.ZQgNMHhC-e4r9ZwbIua2tovKz99US-PfywYuXEQSGgs

    {
      "count": 1,
      "name": "123",
      "price": 10000,
      "productId" : 1
    }

### 상품 수정
PUT http://localhost:8082/seller/product
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0QnRyc3BBMWM0Z1MvSFRGcHBZYkxqTnQ4YXBkSmxYOG54djlYamhYNkJFPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjgwMzEzMzMzLCJleHAiOjE2ODAzOTk3MzN9.ZQgNMHhC-e4r9ZwbIua2tovKz99US-PfywYuXEQSGgs

{
  "description": "상품설명",
  "items": [
    {
      "id": 1,
      "count": 1,
      "name": "234",
      "price": 10000
    }
  ],
  "id": 1,
  "name": "나이키 에어포스"
}

### 상품 아이템 수정
PUT http://localhost:8082/seller/product/item
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0QnRyc3BBMWM0Z1MvSFRGcHBZYkxqTnQ4YXBkSmxYOG54djlYamhYNkJFPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjgwMzEzMzMzLCJleHAiOjE2ODAzOTk3MzN9.ZQgNMHhC-e4r9ZwbIua2tovKz99US-PfywYuXEQSGgs

{
  "count": 1,
  "name": "123",
  "price": 10000,
  "id" : 1
}

### 상품 삭제
DELETE http://localhost:8082/seller/product?id=1
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0QnRyc3BBMWM0Z1MvSFRGcHBZYkxqTnQ4YXBkSmxYOG54djlYamhYNkJFPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjgwMzEzMzMzLCJleHAiOjE2ODAzOTk3MzN9.ZQgNMHhC-e4r9ZwbIua2tovKz99US-PfywYuXEQSGgs


### 상품 아이템 삭제
DELETE http://localhost:8082/seller/product/item?id=2
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0QnRyc3BBMWM0Z1MvSFRGcHBZYkxqTnQ4YXBkSmxYOG54djlYamhYNkJFPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjgwMzEzMzMzLCJleHAiOjE2ODAzOTk3MzN9.ZQgNMHhC-e4r9ZwbIua2tovKz99US-PfywYuXEQSGgs

### 상품 검색
GET http://localhost:8082/search/product?name=나이키
Content-Type: application/json

### 상품 디테일 검색
GET http://localhost:8082/search/product/detail?productId=2
Content-Type: application/json

